\c data
CREATE SCHEMA data;
GRANT ALL PRIVILEGES ON SCHEMA data TO pi5ha;
ALTER ROLE pi5ha SET search_path TO data, public;
SET search_path TO data;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA data TO pi5ha;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO pi5ha;
GRANT ALL PRIVILEGES ON SCHEMA public TO pi5ha;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO pi5ha;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO pi5ha;
ALTER DEFAULT PRIVILEGES IN SCHEMA data GRANT ALL PRIVILEGES ON TABLES TO pi5ha;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO pi5ha;
ALTER SCHEMA public OWNER TO pi5ha;
ALTER SCHEMA data OWNER TO pi5ha;
