\c data
CREATE SCHEMA data;
GRANT ALL PRIVILEGES ON SCHEMA data TO pythonuser;
ALTER ROLE pythonuser SET search_path TO data, public;
SET search_path TO data;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA data TO pythonuser;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO pythonuser;
GRANT ALL PRIVILEGES ON SCHEMA public TO pythonuser;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO pythonuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO pythonuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA data GRANT ALL PRIVILEGES ON TABLES TO pythonuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO pythonuser;
ALTER SCHEMA public OWNER TO pythonuser;
ALTER SCHEMA data OWNER TO pythonuser;
